---

- hosts: masters
  remote_user: "{{ ansible_ssh_user }}"
  become: true

  tasks:

  - name: Create a k8s namespace
    community.kubernetes.k8s:
      name: "{{ kubernetes_namespace }}"
      api_version: v1
      kind: Namespace
      state: present

  - name: Deploy IPFS (1/3)
    community.kubernetes.k8s:
      state: present
      namespace: "{{ kubernetes_namespace }}"
      template: k8s-definitions/ipfs-staging-deployment.yaml

  - name: Deploy IPFS (2/3)
    community.kubernetes.k8s:
      state: present
      namespace: "{{ kubernetes_namespace }}"
      template: k8s-definitions/ipfs-staging-internal-service.yaml

  - name: Deploy IPFS (3/3)
    community.kubernetes.k8s:
      state: present
      namespace: "{{ kubernetes_namespace }}"
      template: k8s-definitions/ipfs-staging-external-service.yaml

  - name: Deploy Mongo (1/2)
    community.kubernetes.k8s:
      state: present
      namespace: "{{ kubernetes_namespace }}"
      template: k8s-definitions/mongo-staging-deployment.j2

  - name: Deploy Mongo (2/2)
    community.kubernetes.k8s:
      state: present
      namespace: "{{ kubernetes_namespace }}"
      template: k8s-definitions/mongo-staging-service.yaml

  - name: Deploy westegg (1/2)
    community.kubernetes.k8s:
      state: present
      namespace: "{{ kubernetes_namespace }}"
      template: k8s-definitions/westegg-staging-deployment.j2

  - name: Deploy westegg (2/2)
    community.kubernetes.k8s:
      state: present
      namespace: "{{ kubernetes_namespace }}"
      template: k8s-definitions/westegg-staging-service.yaml
