---
- hosts: masters
  remote_user: "{{ ansible_ssh_user }}"
  become: true

  tasks:
    - name: Create a k8s namespace
      become_user: "{{ ansible_ssh_user }}"
      community.kubernetes.k8s:
        name: westegg-staging
        api_version: v1
        kind: Namespace
        state: present

    - name: Deploy IPFS
      become_user: "{{ ansible_ssh_user }}"
      community.kubernetes.k8s:
        state: present
        namespace: westegg-staging
        template: k8s-definitions/staging/ipfs.yaml.j2

    - name: Deploy WebRTC Star
      become_user: "{{ ansible_ssh_user }}"
      community.kubernetes.k8s:
        state: present
        namespace: westegg-staging
        template: k8s-definitions/staging/webrtc-star.yaml.j2

    - name: Deploy Mongo
      become_user: "{{ ansible_ssh_user }}"
      community.kubernetes.k8s:
        state: present
        namespace: westegg-staging
        template: k8s-definitions/staging/mongo.yaml.j2

    - name: Deploy westegg
      become_user: "{{ ansible_ssh_user }}"
      community.kubernetes.k8s:
        state: present
        namespace: westegg-staging
        template: k8s-definitions/staging/westegg.yaml.j2
