apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfs-staging
spec:
  selector:
    matchLabels:
      app: ipfs
  replicas: 1
  template:
    metadata:
      labels:
        app: ipfs
    spec:
      containers:
      - name: ipfs
        image: ipfs/go-ipfs:bifrost-latest
        ports:
        - containerPort: 4001
        - containerPort: 8081
        - containerPort: 8080
        - containerPort: 5001
