apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-staging
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4.1
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "root"
        - name: MONGO_INITDB_DATABASE
          value: "gatsby"
        - name: MONGO_API_USER
          value: "gatsby"
        - name: MONGO_API_PASS
          value: "gatsby"
        volumeMounts:
          - name: mongo-initdb
            mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mongo-initdb
          configMap:
            name: mongo-initdb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-initdb-config
data:
  mongo-init.sh: |
    #/bin/bash
    set -e

    mongo <<EOF
    use admin
    db.createUser(
      {
        user: "gatsby",
        pwd: "gatsby",
        roles: [
          {
            role: "readWrite",
            db: "gatsby"
          }
        ]
      }
    )
    EOF
