---

- hosts: workers
  remote_user: "{{ ansible_ssh_user }}"
  become: true

  tasks:

  # TODO: Better path handling
  - name: Copy setup command script to node
    copy:
      src: ./master-test-node/root/setup-worker.sh
      dest: /root
      mode: '0700'

  # TODO: Check if node is already setup
  - name: Setup worker from master node command
    shell: /root/setup-worker.sh

  - name: Download calico binary
    get_url:
      url: https://github.com/projectcalico/cni-plugin/releases/download/v3.14.0/calico-amd64
      dest: /opt/cni/bin/calico
      mode: '0755'

  - name: Download calico-ipam binary
    get_url:
      url: https://github.com/projectcalico/cni-plugin/releases/download/v3.14.0/calico-ipam-amd64
      dest: /opt/cni/bin/calico-ipam
      mode: '0755'

  - name: Create k8s CNI config dir
    file:
      path: /etc/cni/net.d
      state: directory
      mode: 0755

  # TODO: Better path handling for config location
  - name: Copy cni config to k8s config dir
    copy:
      src: ./master-test-node/etc/cni/config/cni.kubeconfig
      dest: /etc/cni/net.d/calico-kubeconfig
      mode: '0600'

  - name: Write cni network config
    copy:
      dest: /etc/cni/net.d/10-calico.conflist
      src: ./config/10-calico.conflist
      mode: '0600'
