---
- hosts: masters
  remote_user: "{{ ansible_ssh_user }}"
  become: true

  tasks:
    - name: Check if cluster is already initialized
      shell: /bin/ss -tln | grep ":6443 " | sed -e 's/.*\///'
      register: ss_result

    - name: Initialize K8s cluster with kubeadm
      shell: "kubeadm init --node-name {{ ansible_hostname }} --pod-network-cidr=192.168.0.0/16 > /var/log/kubeadm_init.log"
      when: not "6443" in ss_result.stdout

    - name: Copy worker node setup command to file
      shell: tail -2 /var/log/kubeadm_init.log > /root/setup-worker.sh

    - name: Fetch setup command for worker nodes
      fetch:
        src: /root/setup-worker.sh
        dest: "./master-node-files"

    - name: Setup kubeconfig for non-root user (1/2)
      become_user: "{{ ansible_ssh_user }}"
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Setup kubeconfig for non-root user (2/2)
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ ansible_ssh_user }}/.kube/config
        remote_src: yes
        owner: "{{ ansible_ssh_user }}"

    - name: Create local tmp directory
      become_user: "{{ ansible_ssh_user }}"
      local_action: file
      args:
        path: ./tmp
        state: directory

    # https://docs.projectcalico.org/getting-started/kubernetes/quickstart
    - name: Install Tigera Calico operator (1/2)
      become_user: "{{ ansible_ssh_user }}"
      local_action: get_url
      args:
        url: https://docs.projectcalico.org/manifests/tigera-operator.yaml
        dest: ./tmp/tigera-operator.yaml

    - name: Install Tigera Calico operator (2/2)
      become_user: "{{ ansible_ssh_user }}"
      community.kubernetes.k8s:
        template: ./tmp/tigera-operator.yaml
        state: present

    - name: Install Calico custom resource (1/2)
      become_user: "{{ ansible_ssh_user }}"
      local_action: get_url
      args:
        url: https://docs.projectcalico.org/manifests/custom-resources.yaml
        dest: ./tmp/custom-resources.yaml

    - name: Install Calico custom resource (2/2)
      become_user: "{{ ansible_ssh_user }}"
      community.kubernetes.k8s:
        template: ./tmp/custom-resources.yaml
        state: present

    - name: Allow master node to run pods
      become_user: "{{ ansible_ssh_user }}"
      shell: kubectl taint nodes --all node-role.kubernetes.io/master-
