apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfs-staging
spec:
  selector:
    matchLabels:
      app: ipfs-staging
  replicas: 1
  template:
    metadata:
      labels:
        app: ipfs-staging
    spec:
      containers:
      - name: ipfs
        image: gatsbytv/go-ipfs:v0.8.0
        ports:
        - containerPort: 4001
        - containerPort: 8081
        - containerPort: 8080
        - containerPort: 5001
