apiVersion: v1
kind: Service
metadata:
  name: mongodb-staging
  labels:
    app: mongodb-staging
spec:
  ports:
  - port: 27017
    name: mongodb
    protocol: TCP
  selector:
    app: mongodb-staging
  type: ClusterIP
