apiVersion: apps/v1
kind: Deployment
metadata:
  name: webrtc-star-staging
spec:
  selector:
    matchLabels:
      app: webrtc-star-staging
  replicas: 1
  template:
    metadata:
      labels:
        app: webrtc-star-staging
    spec:
      containers:
      - name: webrtc-star
        image: libp2p/js-libp2p-webrtc-star
        ports:
        - containerPort: 9090
