apiVersion: v1
kind: Service
metadata:
  name: westegg-staging
  labels:
    app: westegg-staging
spec:
  ports:
  - port: 3001
    name: nodejs
    protocol: TCP
  selector:
    app: westegg-staging
  type: NodePort
